# Site settings
title: Brian Annis
email: your-email@domain.com
url: https://brianannis.github.io
description: "Deus ex automatopoetus"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '000000'
  links: '#219ab3'

# Footer settings
footer: Brian Annis

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/b_annis
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url: http://bitbucket.org/brianannis
  - title: github
    url: https://github.com/brianannis

# Build settings
markdown: kramdown
permalink: pretty
