# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Annis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Automation Engineer
baseurl: "/brianannis.github.io" # the subpath of your site, e.g. /blog
url: "https://brianannis.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: b_annis
github_username:  brianannis
facebook_username:

# Address information
address_street: 
address_city: New York
address_state: NY
address_zip: 10003

# Build settings
markdown: kramdown
permalink: pretty